# Generated by Django 5.1.7 on 2025-04-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_assigned_to_activity_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
